CREATE TABLE IF NOT EXISTS users_balance (
id BIGSERIAL PRIMARY KEY,
user_id BIGINT NOT NULL UNIQUE,
balance NUMERIC(15,2) NOT NULL
);

CREATE TABLE IF NOT EXISTS pay_operation (
id BIGSERIAL PRIMARY KEY,
user_id BIGINT NOT NULL,
operation_date TIMESTAMP NOT NULL,
operation_type VARCHAR(100) NOT NULL,
amount NUMERIC(15,2) NOT NULL
);
